name: Publish Documentation

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v4.0.0
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 26
          cache: "pnpm"
      - name: Install packages
        run: pnpm install

      - name: Build
        run: pnpm run docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: docs
          folder: docs
